// this file is no longer used since database feature was added.

const galleryItems = [
    { id: 1, path: "images/myst.jpg", title: 'Myst', description: 'Myst was unlike anything before, it created a new genre of adventure game and was pretty much all I could think about in kindergarden. With stunning visuals and an atmospheric soundtrack, Myst topped video game sales records for almost a decade, and is partially responsible for the widespread adoption of the CD-ROM drive.', likes: 0 },
    { id: 2, path: "images/duckGame.jpg", title: 'Duck Game', description: 'I\'ve played about 2,500 hours of Duck Game. It\'s a multi-player game where everyone is a cute duck with a funny hat and also you\'re all trying to kill each other. It has a button for quacking, so most of the audio is mix of gunfire, explosions, and duck quacks. It\'s the stupidest funniest game I\'ve ever seen!', likes: 0 },
    { id: 3, path: "images/cavesOfQud.jpg", title: 'Cave of Qud',  description: 'Caves of Qud is an incredible roguelike set in an amazing post-human world where water is the only currency. The player takes the role of a mutated techno-augmented wanderer and digs through artifacts of ancient civilizations to learn the rich lore of the world.', likes: 0 },
    { id: 4, path: "images/darkSouls.jpg", title: 'Dark Souls',  description: 'Dark souls redefined difficulty in video games, and showed developers that many players still want challenging games. It also took up way too much of my time during college.', likes: 0 },
    { id: 5, path: "images/portal.jpg", title: 'Portal',  description: 'Portal is a perfect synthesis of humor and puzzle-solving. It introduced moveable portal mechanics which allowed players to move through a game world in ways that had never been seen before.', likes: 0 },
    { id: 6, path: "images/witness.jpg", title: 'The Witness',  description: 'The Witness is a puzzle game that slowly teaches players its own symbolic syntax without using words. The way you learn to read its puzzles reminds me of programming languages.', likes: 0 },
    { id: 7, path: "images/beatSaber.jpg", title: 'Beat Saber',  description: 'Beat Saber is an excellent VR rhythm game that helps keep me in shape! It\'s so fun that you won\'t even realize you\'re exhaused until you collapse on the floor!', likes: 0 },
    { id: 8, path: "images/baldursGate.jpg", title: 'The Witness',  description: `From the makers of "Fallout", Baldur's Gate founded the genre of the isometric D20 system (D&D) RPG. With beautiful artwork and masterful storytelling the Baldur's Gate series was a milestone in the history of gaming.`, likes: 0 },
    { id: 9, path: "images/factorio.jpg", title: 'Factorio',  description: 'Factorio is a logistical planning game that requires the player to build massive factories on an alien planet. Similar to programming, it forces you to invent novel solutions to interesting problems.', likes: 0 },
    { id: 10, path: "images/kenshi.jpg", title: 'Kenshi',  description: 'Kenshi is an unusual hybrid of the RPG and city-building generes. It\'s unique engine allows for the control of multiple characters across a massive game world.', likes: 0 },
    { id: 11, path: "images/sunlessSea.jpg", title: 'Sunless Sea',  description: 'Sunless Sea is a moody, story-driven game where you play as the captain of ship sailing a subterranean ocean. Lovecraftian horror fans will thoroughly enjoy this one.', likes: 0 },
    { id: 12, path: "images/fallout.jpg", title: 'Fallout',  description: 'Fallout is a retrofuturistic post-apocalyptic RPG. It gave players a vibrant scorched wasteland to explore and told a rich story about the remains of humanity after nuclear war.', likes: 0 }
];

module.exports = galleryItems;